"""Build pms_upload.zip containing only deployment files for DirectAdmin.

Run from project root:  python make_deploy_zip.py

Excludes: tests, legacy FastAPI app/, Tally_MIS/, scripts/, docs/, dev DBs,
__pycache__, node_modules, .git, and anything matching *.pyc.
"""
import os
import sys
import zipfile

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(ROOT, 'pms_upload.zip')

# Folders to include (Django project + app + templates + static + migrations)
FOLDERS = [
    'pms_portal',   # Django settings / urls / wsgi
    'core',         # the Django app (models, views, templates, static, migrations)
]

# Top-level files to include
FILES = [
    'manage.py',
    'passenger_wsgi.py',
    'requirements.txt',
    'local_settings.py.example',
    'run_migrate.py',
    'run_collectstatic.py',
    'run_createsuperuser.py',
    'DEPLOY.md',
]

SKIP_DIR_NAMES = {
    '__pycache__',
    '.pytest_cache',
    '.mypy_cache',
    'node_modules',
    '.git',
    'staticfiles',    # regenerated by run_collectstatic.py on the server
    'uploads',        # user data — lives in /home/npcindia/pms_data/ on server
    'tests',          # legacy FastAPI tests
    'tests_django',   # run locally only
    'migrations_backup',
}
SKIP_EXT = {'.pyc', '.pyo', '.pyd', '.log', '.sqlite3', '.db'}


def should_skip_file(name):
    return any(name.endswith(ext) for ext in SKIP_EXT)


def main():
    if os.path.exists(OUT):
        os.remove(OUT)

    added = 0
    with zipfile.ZipFile(OUT, 'w', zipfile.ZIP_DEFLATED) as zf:
        for folder in FOLDERS:
            folder_path = os.path.join(ROOT, folder)
            if not os.path.isdir(folder_path):
                print(f'  (skip) {folder}/ -- not found')
                continue
            for dirpath, dirnames, filenames in os.walk(folder_path):
                dirnames[:] = [d for d in dirnames if d not in SKIP_DIR_NAMES]
                for fname in filenames:
                    if should_skip_file(fname):
                        continue
                    # skip local_settings.py if it accidentally exists (contains DB password)
                    if fname == 'local_settings.py':
                        print(f'  (skip) local_settings.py -- contains secrets')
                        continue
                    abs_p = os.path.join(dirpath, fname)
                    rel_p = os.path.relpath(abs_p, ROOT).replace(os.sep, '/')
                    zf.write(abs_p, rel_p)
                    added += 1

        for fname in FILES:
            abs_p = os.path.join(ROOT, fname)
            if not os.path.exists(abs_p):
                print(f'  (skip) {fname} -- not found')
                continue
            zf.write(abs_p, fname)
            added += 1

    size_mb = os.path.getsize(OUT) / (1024 * 1024)
    print(f'\nCreated: {OUT}')
    print(f'Files added: {added}')
    print(f'Zip size:    {size_mb:.2f} MB')


if __name__ == '__main__':
    sys.exit(main())
