# Generated by Django 6.0.3 on 2026-04-22 00:46

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('COST', 'Cost Estimation'), ('MILESTONE', 'Milestones'), ('TEAM', 'Team'), ('REVENUE', 'Revenue Allocation')], max_length=20)),
                ('edit_number', models.IntegerField()),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('change_data', models.TextField(blank=True, default='')),
                ('status', django_fsm.FSMField(default='PENDING', max_length=50)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='core.assignment')),
                ('proposed_by', models.ForeignKey(db_column='proposed_by_officer_id', on_delete=django.db.models.deletion.PROTECT, related_name='edit_requests_proposed', to=settings.AUTH_USER_MODEL, to_field='officer_id')),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by_officer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_requests_reviewed', to=settings.AUTH_USER_MODEL, to_field='officer_id')),
            ],
            options={
                'db_table': 'edit_requests',
                'ordering': ['-proposed_at'],
                'indexes': [models.Index(fields=['assignment', 'section'], name='idx_er_asgn_section'), models.Index(fields=['status'], name='idx_er_status')],
            },
        ),
    ]
