# Generated by Django 6.0.3 on 2026-04-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_edit_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='bulk_onboarding_as_of_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_bulk_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
