# Generated by Django 6.0.3 on 2026-04-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_site_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('ESCALATE', 'Escalate'), ('COMMENT', 'Comment'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=50),
        ),
    ]
