# Generated by Django 6.0.3 on 2026-04-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_extend_activitylog_action_enum'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100, unique=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('running', 'Running')], default='success', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_duration_ms', models.IntegerField(default=0)),
                ('expected_interval_seconds', models.IntegerField(default=86400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cron_heartbeat',
                'ordering': ['job_name'],
            },
        ),
    ]
