# Generated by Django 6.0.3 on 2026-05-30 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_cron_heartbeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreWORecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.CharField(max_length=100, unique=True)),
                ('stage', models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('PRELIM_VISIT', 'Preliminary Visit'), ('PROPOSAL', 'Proposal')], default='ENQUIRY', max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('client', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('domain', models.CharField(blank=True, default='', max_length=100)),
                ('expected_value', models.FloatField(default=0)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('outcome', models.CharField(choices=[('OPEN', 'Open'), ('CONVERTED_TO_WO', 'Converted to WO'), ('DROPPED', 'Dropped'), ('ON_HOLD', 'On Hold')], default='OPEN', max_length=20)),
                ('outcome_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pre_wo_records', to=settings.AUTH_USER_MODEL, to_field='officer_id')),
                ('converted_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_pre_wo_records', to='core.assignment')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pre_wo_records', to=settings.AUTH_USER_MODEL, to_field='officer_id')),
                ('office', models.ForeignKey(db_column='office_id', on_delete=django.db.models.deletion.PROTECT, related_name='pre_wo_records', to='core.office', to_field='office_id')),
                ('owner', models.ForeignKey(blank=True, db_column='owner_officer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_pre_wo_records', to=settings.AUTH_USER_MODEL, to_field='officer_id')),
            ],
            options={
                'db_table': 'pre_wo_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stage'], name='idx_prewo_stage'), models.Index(fields=['outcome'], name='idx_prewo_outcome'), models.Index(fields=['office'], name='idx_prewo_office')],
            },
        ),
    ]
