# Generated by Django 6.0.3 on 2026-05-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_preworecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonrevenuesuggestion',
            name='man_days',
            field=models.FloatField(default=0),
        ),
    ]
