# Generated by Django 6.0.3 on 2026-05-30 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_nonrevenuesuggestion_man_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogramme',
            name='actual_expenditure',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trainingprogramme',
            name='actual_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingprogramme',
            name='completion_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingprogramme',
            name='fy_period',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingprogramme',
            name='invoice_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trainingprogramme',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogramme',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trainingprogramme',
            name='payment_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trainingprogramme',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogramme',
            name='payment_recorded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingprogramme',
            name='revenue_recognized_20',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trainingprogramme',
            name='revenue_recognized_80',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='TrainingRevenueLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_type', models.CharField(choices=[('COMPLETION_80', '80% on Completion'), ('PAYMENT_20', '20% on Payment')], max_length=20)),
                ('share_percent', models.FloatField()),
                ('amount', models.FloatField()),
                ('fy_period', models.CharField(blank=True, default='', max_length=20)),
                ('transaction_date', models.DateField()),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(db_column='officer_id', on_delete=django.db.models.deletion.PROTECT, related_name='training_revenue_ledger', to=settings.AUTH_USER_MODEL, to_field='officer_id')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_ledger', to='core.trainingprogramme')),
            ],
            options={
                'db_table': 'training_revenue_ledger',
                'indexes': [models.Index(fields=['officer'], name='idx_trl_officer'), models.Index(fields=['programme'], name='idx_trl_programme')],
            },
        ),
    ]
