# Generated by Django 6.0.3 on 2026-05-30 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_trainingprogramme_actual_expenditure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueAllocationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ADDRESSED', 'Addressed'), ('WITHDRAWN', 'Withdrawn')], default='OPEN', max_length=20)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('addressed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addressed_by', models.ForeignKey(blank=True, db_column='addressed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addressed_revenue_flags', to=settings.AUTH_USER_MODEL, to_field='officer_id')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_flags', to='core.assignment')),
                ('raised_by', models.ForeignKey(db_column='raised_by', on_delete=django.db.models.deletion.PROTECT, related_name='raised_revenue_flags', to=settings.AUTH_USER_MODEL, to_field='officer_id')),
                ('revenue_share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags', to='core.revenueshare')),
            ],
            options={
                'db_table': 'revenue_allocation_flags',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assignment'], name='idx_flag_assignment'), models.Index(fields=['status'], name='idx_flag_status')],
            },
        ),
    ]
