# Generated by Django 6.0.3 on 2026-05-31 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_revenueallocationflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingExpenseHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=0)),
                ('head_code', models.CharField(max_length=20, unique=True)),
                ('head_name', models.CharField(max_length=300)),
                ('macro_category', models.CharField(choices=[('FEE', 'Fees & Honorarium'), ('TRAVEL', 'Travel & Conveyance'), ('LODGING', 'Lodging & Boarding'), ('MATERIAL', 'Material, Kit & Publication'), ('ADMIN', 'Administrative & Event'), ('MISC', 'Miscellaneous & Unforeseen')], default='MISC', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'training_expense_heads',
                'ordering': ['seq', 'head_code'],
            },
        ),
        migrations.AddField(
            model_name='expenditurehead',
            name='macro_category',
            field=models.CharField(choices=[('FEE', 'Fees & Honorarium'), ('TRAVEL', 'Travel & Conveyance'), ('LODGING', 'Lodging & Boarding'), ('MATERIAL', 'Material, Kit & Publication'), ('ADMIN', 'Administrative & Event'), ('MISC', 'Miscellaneous & Unforeseen')], default='MISC', max_length=20),
        ),
        migrations.CreateModel(
            name='TrainingExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_amount', models.FloatField(default=0)),
                ('actual_amount', models.FloatField(default=0)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.trainingexpensehead')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='core.trainingprogramme')),
            ],
            options={
                'db_table': 'training_expense_items',
                'indexes': [models.Index(fields=['programme'], name='idx_tei_programme')],
                'unique_together': {('programme', 'head')},
            },
        ),
    ]
