# Generated by Django 6.0.3 on 2026-05-31 11:31

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_seed_expense_heads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='workflow_stage',
            field=django_fsm.FSMField(choices=[('REGISTRATION', 'WO Registration'), ('TL_ASSIGNMENT', 'TL Assignment'), ('DETAIL_ENTRY', 'Progressive Fill'), ('ACTIVE', 'Execution'), ('COMPLETED', 'Closure')], default='REGISTRATION', max_length=50),
        ),
    ]
